POST http://localhost:8080/general/balance/12
Content-Type: application/json

{
  "subsidiaries": [24,25],
  "areas": [28,29],
  "to": "2024-12-31",
  "currencies": 72,
  "responsible": ["Sebastian Belmonte", "Micaela Gordillo", "Juan Neves", "Alejandro Flores"]
}
###
POST http://localhost:8080/general/balance/11
Content-Type: application/json

{
  "subsidiaries": [23],
  "areas": [27],
  "to": "2024-12-31",
  "currencies": "BOL",
  "responsible": ["Sebastian Belmonte", "Micaela Gordillo", "Juan Neves", "Alejandro Flores"]
}
