POST http://localhost:8080/api/v1/ms-company/company
Content-Type: multipart/form-data;

{
  "enterprise": {
    "enterpriseName": "ss",
    "dicCategory": "",
    "nit": "ss",
    "enterpriseLocation": "ss",
    "emailRepresentative": "ss@mial.com",
    "nameRepresentative": "ss",
    "ciRepresentative": "ss",
    "numberRepresentative": "12312",
    "numberRegistration": "ss",
    "numberEmployee": "d",
    "rubro": "asd",
    "openingDate": "10-06-2023",
    "subsidiaries": [
      {
        "name": "hola",
        "address": "ss",
        "areas": [
          "mkt",
          "disneo"
        ]
      }
    ]
  },
  "currencyConfig": {
    "currencyList": []
  },
  "accountablePlan": [
    {
      "accountCode": 1,
      "nameAccount": "Activo",
      "moneyRub": true,
      "report": false,
      "classificator": false,
      "level": 0,
      "childrenAccounts": []
    },
    {
      "accountCode": 2,
      "nameAccount": "Pasivo",
      "moneyRub": true,
      "report": false,
      "classificator": false,
      "level": 0,
      "childrenAccounts": []
    },
    {
      "accountCode": 3,
      "nameAccount": "Patrimoinio",
      "moneyRub": true,
      "report": false,
      "classificator": false,
      "level": 0,
      "childrenAccounts": []
    },
    {
      "accountCode": 4,
      "nameAccount": "Ingresos",
      "moneyRub": true,
      "report": false,
      "classificator": false,
      "level": 0,
      "childrenAccounts": []
    },
    {
      "accountCode": 5,
      "nameAccount": "Egresos",
      "moneyRub": true,
      "report": false,
      "classificator": false,
      "level": 0,
      "childrenAccounts": []
    }
  ]
}
#######################

GET http://localhost:8080/config/enterprise/3

#######################

GET http://localhost:8080/config/enterprise/currency/8
