POST http://localhost:8080/api/v1/ms-company/company
Content-Type: multipart/form-data;

{
  "enterprise": {
    "enterpriseName": "Example Name",
    "dicCategory": "Technology",
    "nit": "167242123132",
    "enterpriseLocation": "Av. Ejemplo",
    "contactMail": "example@gmail.com",
    "contactName": "Name Of Contact",
    "logo64b": "hjdahjsidhjaohdioaho88221jiubiudbuibui4vjihugufydtdtyddytdytdtdytdytdytdytdtydytdtybiu",
    "subsidiaries": [
      {
        "name": "example name",
        "address": "address example",
        "areas": ["area1", "area2", "area3"]
      },
      {
        "name": "example name 2",
        "address": "address example 2",
        "areas": ["area12", "area22", "area32"]
      }
    ],
    "openingDate": "09-11-2023"

  },
  "currencyConfig": {
    "principalCurrency": 0,
    "currencyList": [
      {
        "moneyName": "Dolares",
        "abbreviationName": "USD",
        "currency": 0
      },
      {
        "moneyName": "Crypto Moneda",
        "abbreviationName": "CM",
        "currency": 0
      }
    ]
  },
  "accountablePlan": [
    {
      "accountCode": "1",
      "nameAccount": "Pasivo",
      "moneyRub": true,
      "report": true,
      "classificator": true,
      "level": 1,
      "childrenAccounts": [
        {
          "accountCode": "11",
          "nameAccount": "Pasivo Corriente",
          "moneyRub": true,
          "report": true,
          "classificator": true,
          "level": 2,
          "childrenAccounts": [
            {
              "accountCode": "111",
              "nameAccount": "Pasivo Corriente Secundario Hijo",
              "moneyRub": true,
              "report": true,
              "classificator": false,
              "level": 3,
              "childrenAccounts": []
            }
          ]
        },
        {
          "accountCode": "12",
          "nameAccount": "Pasivo Corriente Fijo",
          "moneyRub": true,
          "report": true,
          "classificator": false,
          "level": 2,
          "childrenAccounts": []
        }
      ]
    },
    {
      "accountCode": "2",
      "nameAccount": "Activo",
      "moneyRub": true,
      "report": true,
      "classificator": true,
      "level": 1,
      "childrenAccounts": []
    }
  ]
}

#######################

GET http://localhost:8080/config/enterprise/10
