POST http://localhost:8080/general/estado-resultados/11
Content-Type: application/json

{
  "subsidiaries": [23],
  "areas": [27],
  "to": "2024-12-31",
  "currencies": "BOL",
  "responsible": ["Sebastian Belmonte", "Micaela Gordillo", "Juan Neves", "Alejandro Flores"]
}
