POST http://localhost:8080/diary/book/2
Content-Type: application/json

{
  "subsidiaries": [2,3],
  "areas": [2,3],
  "from": "2021-01-01",
  "to": "2024-12-31",
  "transactionType": 2,
  "currencies": 19
}

###


