
POST http://localhost:8080/mayor/book/5
Content-Type: application/json

{
  "subsidiaries": [9],
  "areas": [9],
  "from": "2020-01-01T00:00:00Z",
  "to": "2023-12-12T00:00:00Z",
  "accountsId": [94],
  "currencies": 19
}


###

POST http://localhost:8080/mayor/book/6
Content-Type: application/json

{
  "subsidiaries": [11,12],
  "areas": [11,12],
  "from": "2020-01-01T00:00:00Z",
  "to": "2023-12-12T00:00:00Z",
  "accountsId": [114,115],
  "currencies": 26
}