server:
  port: ${PORT_MS:8080}


spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:postgresql://abcount.c1v0paixfk4r.us-west-2.rds.amazonaws.com/abcount}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  sql:
    init:
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
custom-config:
  master-access-key: abcount
  master-secret-key: sucha1234
keycloak:
  config:
    import: optional:file:.env[.properties]
  realm: abcount
  auth-server-url: https://mihouodie.com
  autodetect-bearer-only: true
  ssl-required: none
  resource: backend
  credentials:
    secret: KQotk9NbUnrNWfnYdzX8XAe5N7eiqtxD
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - USER
      security-collections:
        - name: SOME USER SERVICE
          methods:
            - GET
            - POST
            - PUT
            - DELETE
          patterns:
            - /apia/v1/user/*
    - auth-roles:
        - ADMIN
      security-collections:
        - name: SOME ADMIN SERVICE
          methods:
            - PUT
            - GET
            - POST
          patterns:
            - /apia/v1/admin/*
minio:
  url: ${MINIO_URL:http://104.248.232.102:9000}
  bucket: ${MINIO_BUCKET:abcount}
  access-key: ${MINIO_ACCESS_KEY:gTErsD7Nhh2qUfXlIfIx}
  secret-key: ${MINIO_SECRET_KEY:d7y2rORndi3wS8mXM3Zmdo3SXNI0VOhrfB7XIkk5}
