server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://54.71.239.115:5432/abcount
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sucha1234
  sql:
    init:
      mode: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true