server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  sql:
    init:
      mode: always